# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'tn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tn

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Firestore'
pod 'IQKeyboardManagerSwift'
pod 'FirebaseFirestoreSwift'

  target 'tnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tnUITests' do
    # Pods for testing
  end

end
