# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'IQKeyboardManagerSwift'


pod 'Firebase/Firestore'
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for tn

  target 'tnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tnUITests' do
    # Pods for testing
  end

end
